application: sa3album
version: 1
runtime: python27
threadsafe: true
api_version: 1
derived_file_type:
- python_precompiled

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon
  expiration : "10d"

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /static
  static_dir: static
  expiration: "30d"
  
- url: /a/.*
  script: admin.app
  login: admin
  
- url: /remote_api
  script: google.appengine.ext.remote_api.handler.application
  login: admin
  
- url: /api/.*
  script: api.app

- url: .*
  script: main.app
  
